/**
 * Minimal TypeScript shape of the Supabase tables.
 * Keep these in sync with supabase/schema.sql.
 *
 * If you outgrow this you can replace it with the autogenerated types via:
 *   `npx supabase gen types typescript --project-id <ref> > src/types/database.gen.ts`
 */

export type UUID = string;
export type ISODate = string;
export type ISOTimestamp = string;

export interface UserRow {
  id: UUID;
  email: string;
  display_name: string | null;
  avatar_url: string | null;
  created_at: ISOTimestamp;
  updated_at: ISOTimestamp;
}

export interface PortfolioRow {
  id: UUID;
  user_id: UUID;
  cash_balance: number;
  starting_balance: number;
  created_at: ISOTimestamp;
  updated_at: ISOTimestamp;
}

export interface HoldingRow {
  id: UUID;
  portfolio_id: UUID;
  symbol: string;
  quantity: number;
  avg_cost: number;
  created_at: ISOTimestamp;
  updated_at: ISOTimestamp;
}

export interface TransactionRow {
  id: UUID;
  portfolio_id: UUID;
  symbol: string;
  side: "buy" | "sell";
  quantity: number;
  price: number;
  total: number;
  realized_pnl: number | null;
  executed_at: ISOTimestamp;
}

export interface StockPriceRow {
  symbol: string;
  name: string;
  price: number;
  change: number;
  change_pct: number;
  prev_close: number;
  day_high: number | null;
  day_low: number | null;
  market_cap: number | null;
  volume: number | null;
  updated_at: ISOTimestamp;
}

export interface StockHistoryRow {
  symbol: string;
  trade_date: ISODate;
  open: number | null;
  high: number | null;
  low: number | null;
  close: number;
  volume: number | null;
}

export interface WatchlistRow {
  id: UUID;
  user_id: UUID;
  symbol: string;
  created_at: ISOTimestamp;
}

export interface AchievementRow {
  code: string;
  title: string;
  description: string;
  icon: string;
  threshold: number | null;
  category: string;
}

export interface UserAchievementRow {
  user_id: UUID;
  achievement_code: string;
  unlocked_at: ISOTimestamp;
}

export interface PortfolioSnapshotRow {
  id: UUID;
  portfolio_id: UUID;
  snapshot_date: ISODate;
  cash_balance: number;
  holdings_value: number;
  total_value: number;
  created_at: ISOTimestamp;
}
